<?php

namespace ContainerIyxKqqF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7qVbNDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7qVbNDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7qVbNDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', '.errored..service_locator.7qVbNDB.Symfony\\Component\\PasswordHasher\\PasswordHasherInterface', NULL, 'Cannot autowire service ".service_locator.7qVbNDB": it references interface "Symfony\\Component\\PasswordHasher\\PasswordHasherInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'passwordHasher' => 'Symfony\\Component\\PasswordHasher\\PasswordHasherInterface',
        ]);
    }
}
