<?php

namespace ContainerIyxKqqF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordHasherInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7qVbNDB.Symfony\Component\PasswordHasher\PasswordHasherInterface' shared service.
     *
     * @return \Symfony\Component\PasswordHasher\PasswordHasherInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7qVbNDB": it references interface "Symfony\\Component\\PasswordHasher\\PasswordHasherInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
