<?php

namespace ContainerJ6LUF57;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_HKnGI4PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.hKnGI4P' shared service.
     *
     * @return \App\Controller\Employee\logi
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Employee\\UserController::login()": the $JWTToken argument is type-hinted with the non-existent class or interface: "App\\Controller\\Employee\\logi". Did you forget to add a use statement?');
    }
}
