<?php

namespace ContainerJ6LUF57;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SQ9sLZAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SQ9sLZA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SQ9sLZA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'JWTToken' => ['privates', '.errored.hKnGI4P', NULL, 'Cannot determine controller argument for "App\\Controller\\Employee\\UserController::login()": the $JWTToken argument is type-hinted with the non-existent class or interface: "App\\Controller\\Employee\\logi". Did you forget to add a use statement?'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'JWTToken' => '?',
            'passwordHasher' => '?',
        ]);
    }
}
