<?php

namespace ContainerTM7BPfw;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6uI72bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q6uI72b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q6uI72b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Employee\\UserController::create' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\Employee\\UserController::createAdmin' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\Employee\\UserController::login' => ['privates', '.service_locator.e614KQq', 'get_ServiceLocator_E614KQqService', true],
            'App\\Controller\\MailerController::sendEmail' => ['privates', '.service_locator.9BtWHRI', 'get_ServiceLocator_9BtWHRIService', true],
            'App\\Controller\\ResetPasswordController::changePassword' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\ResetPasswordController::resetPassword' => ['privates', '.service_locator.byPgMfB', 'get_ServiceLocator_ByPgMfBService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Employee\\UserController:create' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\Employee\\UserController:createAdmin' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\Employee\\UserController:login' => ['privates', '.service_locator.e614KQq', 'get_ServiceLocator_E614KQqService', true],
            'App\\Controller\\MailerController:sendEmail' => ['privates', '.service_locator.9BtWHRI', 'get_ServiceLocator_9BtWHRIService', true],
            'App\\Controller\\ResetPasswordController:changePassword' => ['privates', '.service_locator.rDMu6Zd', 'get_ServiceLocator_RDMu6ZdService', true],
            'App\\Controller\\ResetPasswordController:resetPassword' => ['privates', '.service_locator.byPgMfB', 'get_ServiceLocator_ByPgMfBService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Employee\\UserController::create' => '?',
            'App\\Controller\\Employee\\UserController::createAdmin' => '?',
            'App\\Controller\\Employee\\UserController::login' => '?',
            'App\\Controller\\MailerController::sendEmail' => '?',
            'App\\Controller\\ResetPasswordController::changePassword' => '?',
            'App\\Controller\\ResetPasswordController::resetPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Employee\\UserController:create' => '?',
            'App\\Controller\\Employee\\UserController:createAdmin' => '?',
            'App\\Controller\\Employee\\UserController:login' => '?',
            'App\\Controller\\MailerController:sendEmail' => '?',
            'App\\Controller\\ResetPasswordController:changePassword' => '?',
            'App\\Controller\\ResetPasswordController:resetPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
