<?php

namespace ContainerXhUFwnW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Bgqk17iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Bgqk17i' shared service.
     *
     * @return \http\Env\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Employee\\EmpPositionsController::create()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".');
    }
}
