<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHPuAFhk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHPuAFhk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHPuAFhk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHPuAFhk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHPuAFhk\App_KernelDevDebugContainer([
    'container.build_hash' => 'HPuAFhk',
    'container.build_id' => 'df82ea77',
    'container.build_time' => 1661245738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHPuAFhk');
