<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1g5NoD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1g5NoD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1g5NoD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1g5NoD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO1g5NoD\App_KernelDevDebugContainer([
    'container.build_hash' => 'O1g5NoD',
    'container.build_id' => '54c1c49d',
    'container.build_time' => 1661829030,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1g5NoD');
