<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'all_department' => [[], ['_controller' => 'App\\Controller\\Employee\\EmDepartmentController::getAll'], [], [['text', '/department']], [], [], []],
    'create_department' => [[], ['_controller' => 'App\\Controller\\Employee\\EmDepartmentController::create'], [], [['text', '/department/create']], [], [], []],
    'update_department' => [['id'], ['_controller' => 'App\\Controller\\Employee\\EmDepartmentController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/department/update']], [], [], []],
    'delete_department' => [['id'], ['_controller' => 'App\\Controller\\Employee\\EmDepartmentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/department/delete']], [], [], []],
    'show_department' => [['id'], ['_controller' => 'App\\Controller\\Employee\\EmDepartmentController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/department']], [], [], []],
    'get_user' => [[], ['_controller' => 'App\\Controller\\Employee\\UserController::getAllUser'], [], [['text', '/user']], [], [], []],
    'create_user' => [[], ['_controller' => 'App\\Controller\\Employee\\UserController::create'], [], [['text', '/api/user/create']], [], [], []],
    'login_user' => [[], ['_controller' => 'App\\Controller\\Employee\\UserController::login'], [], [['text', '/api/login']], [], [], []],
    'update_user' => [['id'], ['_controller' => 'App\\Controller\\Employee\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/update']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\Employee\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/user/delete']], [], [], []],
    'all_role' => [[], ['_controller' => 'App\\Controller\\Employee\\UserRoleController::getAll'], [], [['text', '/role']], [], [], []],
    'create_role' => [[], ['_controller' => 'App\\Controller\\Employee\\UserRoleController::create'], [], [['text', '/api/role/create']], [], [], []],
    'update_role' => [[], ['_controller' => 'App\\Controller\\Employee\\UserRoleController::update'], [], [['text', '/api/role/update']], [], [], []],
    'delete_role' => [[], ['_controller' => 'App\\Controller\\Employee\\UserRoleController::delete'], [], [['text', '/api/role/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
